name: ci
on:
  push:
    branches:
      - master
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.0', '8.2', '8.4', '8.6', '8.8', '8.10']
        include:
        - os: windows-latest
          ghc: 'latest'
        - os: macOS-latest
          ghc: 'latest'
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-haskell@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Update cabal package database
      run: cabal update
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Build
      run: |
        cabal sdist -z -o .
        cabal get chimera-*.tar.gz
        cd chimera-*/
        cabal build -f-representable all
        cabal build all
    - name: Test
      run: cabal test --test-show-details=direct
    - name: Bench
      run: cabal bench --benchmark-options=-l
    - name: Haddock
      run: cabal haddock
